# Colors
GREEN="\033[1;32m"
BLACK="\033[1;30m"
RED="\033[1;31m"
WHITE="\033[1;97m"
CYAN="\033[1;36m"
LIGHT_CYAN="\033[1;36m"
STRIKE="\033[9m"
ITALIC="\033[3m"
FAINT="\033[2m"
BOLD="\033[1m"
BG="\033[41m"
OFF="\033[m"

# Style
# Calendar
export STYLE_CALENDAR_MONTH="${STYLE_CALENDAR_MONTH:-$GREEN}"
export STYLE_CALENDAR_WEEKDAYS="${STYLE_CALENDAR_WEEKDAYS:-$FAINT}"
export STYLE_CALENDAR_CURRENT_DAY="${STYLE_CALENDAR_CURRENT_DAY:-$BLACK$BG}"
export STYLE_CALENDAR_HL_DAY="${STYLE_CALENDAR_HL_DAY:-$BOLD$RED}"

# Week view
export STYLE_WV_DAY="${STYLE_WV_DAY:-$GREEN}"
export STYLE_WV_EVENT_DELIM="${STYLE_WV_EVENT_DELIM:-$RED / $OFF}"
export STYLE_WV_SUMMARY="${STYLE_WV_SUMMARY:-$CYAN}"
export STYLE_WV_TIME="${STYLE_WV_TIME:-$WHITE}"

# List view
export STYLE_LV="${STYLE_LV:-$FAINT}"

# Day view
export STYLE_DV_ALLDAY="${STYLE_DV_ALLDAY:-$LIGHT_CYAN$ITALIC$FAINT    (allday)   $OFF}"
export STYLE_DV_TIME="${STYLE_DV_TIME:-$LIGHT_CYAN}"
export STYLE_DV_CONFIRMED="${STYLE_DV_CONFIRMED:-$CYAN}"
export STYLE_DV_TENTATIVE="${STYLE_DV_TENTATIVE:-$FAINT$CYAN}"
export STYLE_DV_CANCELLED="${STYLE_DV_CANCELLED:-$STRIKE$CYAN}"
export STYLE_DV_HOUR="${STYLE_DV_HOUR:-$FAINT}"
export STYLE_DV_EMPTYHOUR="${STYLE_DV_EMPTYHOUR:-$FAINT----------------------$OFF}"

# Event preview
export STYLE_EPV_DATETIME="${STYLE_EPV_DATETIME:-$CYAN}"
export STYLE_EPV_LOCATION="${STYLE_EPV_LOCATION:-$GREEN}"
